src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Enum\ProductStatus;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $stock = null;
    
    #[ORM\Column(enumType: ProductStatus::class)]
    private ?ProductStatus $status = null; 






    #[ORM\OneToOne(inversedBy: 'product', cascade: ['persist', 'remove'])]
    private ?Image $Image = null;

    /**
     * @var Collection<int, OrderItem>
     */
    #[ORM\OneToMany(targetEntity: OrderItem::class, mappedBy: 'product')]
    private Collection $OrderItem;

    /**
     * @var Collection<int, Category>
     */
    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'products')]
    private Collection $Category;

    /**
     * @var Collection<int, self>
     */
    #[ORM\ManyToMany(targetEntity: self::class, mappedBy: 'Category')]
    private Collection $products;

    public function __construct()
    {
        $this->OrderItem = new ArrayCollection();
        $this->Category = new ArrayCollection();
        $this->products = new ArrayCollection();
    }




    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    public function getStatus(): ?ProductStatus
    {
        return $this->status;
    }

    public function setStatus(ProductStatus $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getOrderItem(): ?OrderItem
    {
        return $this->OrderItem;
    }

    public function setOrderItem(?OrderItem $OrderItem): static
    {
        $this->OrderItem = $OrderItem;

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->Image;
    }

    public function setImage(?Image $Image): static
    {
        $this->Image = $Image;

        return $this;
    }

    public function addOrderItem(OrderItem $orderItem): static
    {
        if (!$this->OrderItem->contains($orderItem)) {
            $this->OrderItem->add($orderItem);
            $orderItem->setProduct($this);
        }

        return $this;
    }

    public function removeOrderItem(OrderItem $orderItem): static
    {
        if ($this->OrderItem->removeElement($orderItem)) {
            // set the owning side to null (unless already changed)
            if ($orderItem->getProduct() === $this) {
                $orderItem->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getCategory(): Collection
    {
        return $this->Category;
    }

    public function addCategory(Category $category): static
    {
        if (!$this->Category->contains($category)) {
            $this->Category->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): static
    {
        $this->Category->removeElement($category);

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(self $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->addCategory($this);
        }

        return $this;
    }

    public function removeProduct(self $product): static
    {
        if ($this->products->removeElement($product)) {
            $product->removeCategory($this);
        }

        return $this;
    }
}

templates/components/Package/SearchPackages.html.twig
<div {{ attributes }}>
	<div class="mb-5">
		<input class="form-control form-control-lg me-2" type="search" data-model="query" placeholder="Recherchez un produit">
	</div>

	<div class="row">
		{% for product in this.products %}
			<div class="col-md-4 mb-4">
				<div class="card h-100">
					<a href="{{ path('product_details', {id: product.id}) }}">
						<img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">

						<div class="card-body">
							<h5 class="card-title">{{ product.name }}</h5>
						</a>
						<p class="card-text">{{ product.description }}</p>
						<p class="card-text">
							<strong>Prix :</strong>
							{{ product.price }}
							€
						</p>
					</div>
					<div class="card-footer">
						<form action="{{ path('cart_add', {id: product.id}) }}" method="post" class="d-flex justify-content-between">
							<input type="number" name="quantity" value="1" min="1" max="{{ product.stock }}" class="form-control w-50 me-2" {% if product.status.value == 'en_rupture' %} disabled {% endif %}>
							<button type="submit" class="btn btn-success btn-sm" {% if product.status.value == 'en_rupture' %} disabled {% endif %}>
								Ajouter au panier
							</button>
						</form>

					</div>
				</div>
			</div>
		{% endfor %}
	</div>
</div>